2024-01-11 03:15:52,660 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-01-11 03:17:49,818 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: '35.217.9.64'. You may need to add '35.217.9.64' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.217.9.64'. You may need to add '35.217.9.64' to ALLOWED_HOSTS.
2024-01-11 03:17:49,861 [WARNING] django.request: Bad Request: /themes/.git/config
2024-01-11 03:19:01,588 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: '35.217.9.64'. You may need to add '35.217.9.64' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.217.9.64'. You may need to add '35.217.9.64' to ALLOWED_HOSTS.
2024-01-11 03:19:01,606 [WARNING] django.request: Bad Request: /
2024-01-11 03:19:53,325 [INFO] django.utils.autoreload: /app/koodiguru_pilot/settings.py changed, reloading.
